name: flutter_sqlite
description: "Projeto de cadastro usando sqlite e flutter"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.2
  get_it: ^7.6.7
  path: ^1.9.0
  go_router: ^13.2.2
  shared_preferences: ^2.2.2
  lottie: ^3.1.0
  crypto: ^3.0.3
  animations: ^2.0.11
  flutter_slidable: ^3.1.0

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
